In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
import torch
import pose.models.seqHourglass as models

In [ ]:
model = models.ConvLSTMCell(100, 200).cuda(1)

In [ ]:
inputs = torch.rand(1,100, 20, 30).cuda(1)
h = torch.rand(1,200, 20, 30).cuda(1)

In [ ]:
outputs = model(inputs, h)

In [ ]:
outputs[1].shape

In [ ]:
model 

In [ ]:
model = models.Bottleneck(20, 10)

In [ ]:
inputs = torch.rand(1,20, 20, 30)

In [ ]:
model(inputs).shape

In [ ]:
assert 0, 'hi'

In [ ]:
torch.stack([torch.rand(2,2,2) for _ in range(10)], dim=-1).shape

In [ ]:
model = models.Conv2dLSTM(10, 20, 2)

In [ ]:
x, h, c = torch.rand(2, 16, 20, 32, 3), None, None

In [ ]:
output, (hn, cn) = model(x, (h,c))

In [ ]:
cn.shape

In [ ]:
x, h, c = torch.rand(2, 3, 128, 128, 3), None, None

In [ ]:
model = models.Hourglass(models.Bottleneck, 1, 8, 5, 2)

In [ ]:
x.shape

In [ ]:
model(x).shape

In [ ]:
import pdb

In [ ]:
model = models.hg(num_stacks=1, num_blocks=1, num_classes=16, rnn_layers=1)

In [ ]:
checkpoint = torch.load('checkpoint/mpii/hg_s1_b1/checkpoint.pth.tar')

In [ ]:
checkpoint_state_dict = dict(checkpoint['state_dict'])

In [ ]:
checkpoint_state_dict_new = {}
keys = checkpoint_state_dict.keys()

In [ ]:
for key in keys:
    new_key = '.'.join(key.split('.')[1:])
    checkpoint_state_dict_new[new_key] = checkpoint_state_dict[key]

In [ ]:
checkpoint_state_dict_new_ = model.state_dict()

In [ ]:
checkpoint_state_dict_new_.update(checkpoint_state_dict_new)

In [ ]:
model.load_state_dict(checkpoint_state_dict_new_)

In [ ]:
from pycasper.name import Name

In [ ]:
model.state_dict()

In [ ]:
import cv2

In [2]:
from pathlib import Path
from dataloader.ucf_dataloader import ucf_dataloader

In [3]:
rgb_path = 'dataset/UCF101/jpegs_256/'
pose_path = 'dataset/UCF101/openpose_output/'
ucf_list = 'dataloader/UCF_list/'
video_path = 'dataloader/'
ucf_split = 'dataloader/'
heatmap_dir = 'preprocess/heatmaps/'

In [4]:
data = ucf_dataloader(1, 0, rgb_path, pose_path, video_path, heatmap_dir, ucf_list, ucf_split)

Loading existing video dictionary...
Filtered videos retained:  2909
Train 1745, Val 581, Test 581


In [12]:
train, dev, test = data.run()

==> Training data : 1745 frames
==> Validation data : 581 frames
==> Test data : 581 frames


/home/chahuja/bin/conda3/envs/torch/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.


In [18]:
%%timeit
count = 0
for ab in test:
    count+=1

1min 54s ± 17 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
ab[0].keys()

dict_keys(['image', 'heatmaps', 'occlusion', 'frameId'])

In [34]:
ab[0]['occlusion']

[tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([0]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([0]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tensor([1]),
 tenso

In [25]:
count

13

In [10]:
len(ab)

2

In [ ]:
for ab in test:
    break

In [ ]:
import torch

In [1]:
import scipy.io

In [3]:
inputs = scipy.io.loadmat('dataset/Penn_Action/labels/0001.mat')

In [6]:
inputs['x'].shape

(151, 13)